In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression


C:\Users\admin\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\admin\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
Data = pd.read_csv("Data_multiple_linear_regression.csv")
Data.head()

Miscellaneous_Expenses  Food_Innovation_Spend  Advertising     City  \
0               138671.80              167497.20    475918.10  Chicago   
1               153151.59              164745.70    448032.53   Mumbai   
2               102919.55              155589.51    412068.54    Tokyo   
3               120445.85              146520.41    387333.62  Chicago   
4                93165.77              144255.34    370302.42    Tokyo   

      Profit  
0  202443.83  
1  201974.06  
2  201232.39  
3  193083.99  
4  176369.94

In [17]:
X = Data.iloc[:,:-1].values
X

array([[138671.8, 167497.2, 475918.1, 'Chicago'],
       [153151.59, 164745.7, 448032.53, 'Mumbai'],
       [102919.55, 155589.51, 412068.54, 'Tokyo'],
       [120445.85, 146520.41, 387333.62, 'Chicago'],
       [93165.77, 144255.34, 370302.42, 'Tokyo'],
       [101588.71, 134024.9, 366995.36, 'Chicago'],
       [148972.87, 136763.46, 131850.82, 'Mumbai'],
       [147304.06, 132446.13, 328010.68, 'Tokyo'],
       [150492.95, 122690.52, 315747.29, 'Chicago'],
       [110453.17, 125482.88, 309115.62, 'Mumbai'],
       [112368.11, 104061.08, 233294.95, 'Tokyo'],
       [93564.61, 102819.96, 253878.55, 'Mumbai'],
       [129094.38, 96011.75, 253973.44, 'Tokyo'],
       [137269.07, 94140.39, 256798.93, 'Mumbai'],
       [158321.42, 122091.24, 260646.92, 'Tokyo'],
       [124390.84, 116671.61, 265910.23, 'Chicago'],
       [123371.55, 80161.11, 268480.06, 'Mumbai'],
       [146851.58, 96805.16, 286708.31, 'Chicago'],
       [115949.79, 93897.16, 299053.57, 'Tokyo'],
       [155288.11, 88567.

In [18]:
Y = Data.iloc[:,4].values
Y

array([202443.83, 201974.06, 201232.39, 193083.99, 176369.94, 167173.12,
       166304.51, 165934.6 , 162393.77, 159941.96, 156303.95, 154441.4 ,
       151767.52, 144489.35, 142784.65, 140099.04, 137174.93, 135552.37,
       134448.9 , 132958.86, 128656.03, 121495.02, 120534.25, 118915.99,
       118734.04, 117586.34, 115915.54, 115190.31, 113464.38, 111186.64,
       110119.59, 107665.56, 107609.84, 106960.92, 106894.8 , 106661.51,
       100890.19, 100131.14,  91411.06,  91187.76,  88421.91,  87980.83,
        81680.49,  79940.98,  75382.33,  75108.08,  59672.75,  52741.73,
        45855.41,  24863.4 ])

In [8]:
corr = Data.corr()
corr

Miscellaneous_Expenses  Food_Innovation_Spend  \
Miscellaneous_Expenses                1.000000               0.241955   
Food_Innovation_Spend                 0.241955               1.000000   
Advertising                          -0.032154               0.724248   
Profit                                0.200717               0.972900   

                        Advertising    Profit  
Miscellaneous_Expenses    -0.032154  0.200717  
Food_Innovation_Spend      0.724248  0.972900  
Advertising                1.000000  0.747766  
Profit                     0.747766  1.000000

In [9]:
#converting categorical column into numerical values

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [19]:
le = LabelEncoder()
X[:,3] = le.fit_transform(X[:,3])

In [20]:
ct = ColumnTransformer(
    [('one_hot_encoder',OneHotEncoder(categories = 'auto') , [3])],
    remainder= 'passthrough'
)

In [21]:
X = ct.fit_transform(X)
X = X[:,[0,1,3,4,5]]


In [22]:
X.astype(int)

array([[     1,      0, 138671, 167497, 475918],
       [     0,      1, 153151, 164745, 448032],
       [     0,      0, 102919, 155589, 412068],
       [     1,      0, 120445, 146520, 387333],
       [     0,      0,  93165, 144255, 370302],
       [     1,      0, 101588, 134024, 366995],
       [     0,      1, 148972, 136763, 131850],
       [     0,      0, 147304, 132446, 328010],
       [     1,      0, 150492, 122690, 315747],
       [     0,      1, 110453, 125482, 309115],
       [     0,      0, 112368, 104061, 233294],
       [     0,      1,  93564, 102819, 253878],
       [     0,      0, 129094,  96011, 253973],
       [     0,      1, 137269,  94140, 256798],
       [     0,      0, 158321, 122091, 260646],
       [     1,      0, 124390, 116671, 265910],
       [     0,      1, 123371,  80161, 268480],
       [     1,      0, 146851,  96805, 286708],
       [     0,      0, 115949,  93897, 299053],
       [     1,      0, 155288,  88567,   4134],
       [     0,     

In [38]:
#splitting the training and test data

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3 ,random_state = 0)

In [39]:
model = LinearRegression()

In [40]:
model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [41]:
constant = model.intercept_
constant

51168.39042487726

In [42]:
coeff = model.coef_
coeff

array([-1.58229418e+02, -4.63028992e+02,  3.01968165e-02,  7.90840255e-01,
        3.10148566e-02])

In [44]:
#predicting from the model and testing the data

y_predict = model.predict(X_test)
df = pd.DataFrame(data = Y_test,columns = ['y_test'])
df['y_predict'] = y_predict

df

y_test      y_predict
0   113464.38  114464.764722
1   154441.40  142718.884992
2   156303.95  144092.850078
3    87980.83   82766.774894
4   201232.39  190102.927619
5   115190.31  124731.310792
6    91411.06   76626.432613
7   107665.56  108586.968401
8   120534.25  124681.828086
9   176369.94  179549.506399
10  106960.92  106704.625400
11  106661.51   98222.671829
12  115915.54  121131.994055
13  106894.80  100601.189785
14  134448.90  138202.462501

In [45]:
#Predicting based on custom X_values

obs = [0,1,16039,134320,401409]

feature_array = np.array(obs)
feature_array = feature_array.reshape(1,-1)
y_pred_obs = model.predict(feature_array)

round(float(y_pred_obs),2)

169864.99

In [58]:
#For regression problem to get the accuracy of models you may use RMSE, MAE etc.for problems like classification you may use confusion matrix.

#Evaulating the R squared error method 

from sklearn import metrics


model_eval = metrics.r2_score(Y_test,y_predict)
print('R square Error ',model_eval)

R square Error  0.9358680970046408


In [59]:
#Adjusting R sqared error
n= 50
p=5
Adjusted_r_square = 1-(1-model_eval)*(n-1)/(n-p-1)
print('Adjusted_r_square ',Adjusted_r_square)

Adjusted_r_square  0.9285803807551681
